/*
===============================================================================
Magnitude Analysis Script
===============================================================================
Purpose:
    - Quantify and compare data distributions across key business dimensions.
    - Profile customer demographics, product catalog composition, and revenue drivers.
    - Identify top-performing geographic markets, product lines, and high-value customers.

Highlights:
    1. Demographic & Geographic Magnitude:
       - Customer volume breakdown by country
       - Customer volume breakdown by gender
    2. Catalog Distribution & Unit Economics:
       - Product counts across categories
       - Average baseline product cost per category
    3. Revenue & Sales Volume Contribution:
       - Total revenue contribution by product category
       - Total revenue generated per customer (Customer Lifetime Value baseline)
       - Total physical unit distribution across geographic markets

Tables Used:
    - gold.dim_customers : Demographic and geographic customer attributes
    - gold.dim_products  : Product metadata, categories, and manufacturing costs
    - gold.fact_sales    : Transactional order lines, sales revenue, and quantities

SQL Clauses & Functions Used:
    - Aggregate Functions : SUM(), COUNT(), AVG()
    - GROUP BY            : Groups records across categorical dimensions
    - ORDER BY ... DESC   : Ranks outputs from highest to lowest magnitude
    - LEFT JOIN           : Links transaction facts with descriptive dimensions
===============================================================================
*/

-- =============================================================================
-- 1) Customer Demographic & Geographic Distribution
-- =============================================================================

-- Total registered customers grouped and ranked by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY 
    country
ORDER BY 
    total_customers DESC;

-- Total registered customers grouped and ranked by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY 
    gender
ORDER BY 
    total_customers DESC;


-- =============================================================================
-- 2) Product Catalog Composition & Cost Profiles
-- =============================================================================

-- Total number of distinct products offered within each category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY 
    category
ORDER BY 
    total_products DESC;

-- Average product cost across each category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY 
    category
ORDER BY 
    avg_cost DESC;


-- =============================================================================
-- 3) Revenue & Volume Distribution Across Dimensions
-- =============================================================================

-- Total gross sales revenue generated by product category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY 
    p.category
ORDER BY 
    total_revenue DESC;

-- Total gross sales revenue generated per customer (ranked by spend)
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY 
    total_revenue DESC;

-- Total physical quantity of items sold by customer country
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.country
ORDER BY 
    total_sold_items DESC;
